# octocat/.github [another third repository]
# .github/workflows/mirror.yml
name: Mirror
on:
  schedule:
    - cron: "36 */6 * * *"
  workflow_dispatch:
jobs:
  mirror1:
    runs-on: fuchsia-latest
    steps:
      - run: git clone --bare https://fuchsia.googlesource.com/fuchsia .
      - run: git push --mirror "https://sbilly:$GITHUB_TOKEN@github.com/sbilly/fuchsia.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
